name: device_finder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  provider: 6.1.4
  equatable: 2.0.7
  flutter_bloc: 9.1.0
  flutter_blue_plus: 1.34.4
  permission_handler: 11.4.0
  path_provider: 2.1.5
  shared_preferences: 2.5.3
  intl: 0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
